spring:
  application:
    name: Momentum
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=mypassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true

server:
  tomcat:
    relaxed-query-chars: '|,{,},[,],\'
    relaxed-path-chars: '|,{,},[,],\'

app:
  jwt:
    expires-in-ms: 3600000
    secret: myveryverystrongsecret123123