CREATE TABLE todos
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    due            TIMESTAMP WITHOUT TIME ZONE,
    title          VARCHAR(255),
    description    VARCHAR(255),
    status         SMALLINT,
    priority_level SMALLINT,
    user_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE todos
    ADD CONSTRAINT FK_TODOS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);